### ISSUE TITLE
logchecker.phar fails to launch due to missing Resources folder in Symfony

### ISSUE THREAD

**Issue by bpmt9** [OPSnet/Logchecker#15]
```
> php logchecker.phar
```
```
PHP Fatal error:  Uncaught UnexpectedValueException: DirectoryIterator::__construct(phar:///home/username/logchecker.phar/vendor/symfony/console/Command/../Resources/): Failed to open directory: operation failed in phar:///home/username/logchecker.phar/vendor/symfony/console/Command/DumpCompletionCommand.php:152
Stack trace:
#0 phar:///home/username/logchecker.phar/vendor/symfony/console/Command/DumpCompletionCommand.php(152): DirectoryIterator->__construct()
#1 phar:///home/username/logchecker.phar/vendor/symfony/console/Command/DumpCompletionCommand.php(55): Symfony\Component\Console\Command\DumpCompletionCommand->getSupportedShells()
#2 phar:///home/username/logchecker.phar/vendor/symfony/console/Command/Command.php(137): Symfony\Component\Console\Command\DumpCompletionCommand->configure()
#3 phar:///home/username/logchecker.phar/vendor/symfony/console/Application.php(1151): Symfony\Component\Console\Command\Command->__construct()
#4 phar:///home/username/logchecker.phar/vendor/symfony/console/Application.php(1327): Symfony\Component\Console\Application->getDefaultCommands()
#5 phar:///home/username/logchecker.phar/vendor/symfony/console/Application.php(548): Symfony\Component\Console\Application->init()
#6 phar:///home/username/logchecker.phar/vendor/symfony/console/Application.php(534): Symfony\Component\Console\Application->add()
#7 phar:///home/username/logchecker.phar/src/LogcheckerConsole.php(21): Symfony\Component\Console\Application->addCommands()
#8 phar:///home/username/logchecker.phar/bin/logchecker(5): OrpheusNET\Logchecker\LogcheckerConsole->__construct()
#9 /home/username/logchecker.phar(15): require('...')
#10 {main}
  thrown in phar:///home/username/logchecker.phar/vendor/symfony/console/Command/DumpCompletionCommand.php on line 152
```

Seems like the package is missing the folder? Verified and previous release 0.8.0 works.

**Comment by itismadness** [comment]
Fixed in 103937a6d2161cc7f2489beb48e709cbb6b2c807, uploaded new `logchecker.phar` for `0.14.0`.
